# Travis CI script
# This is a skeleton created by zproject.
# You can add hand-written code here.

language: c

os:
- linux
#- osx

sudo: false

compiler:
- gcc

cache:
  pip: true
  ccache: true
  directories:
    - ${TRAVIS_BUILD_DIR}/.srcclone/
    - ${TRAVIS_BUILD_DIR}/.build/
    - ${TRAVIS_BUILD_DIR}/.install/

pkg_src_zeromq_ubuntu14: &pkg_src_zeromq_ubuntu14
- sourceline: 'deb http://download.opensuse.org/repositories/network:/messaging:/zeromq:/git-draft/xUbuntu_14.04/ ./'
  key_url: 'http://download.opensuse.org/repositories/network:/messaging:/zeromq:/git-draft/xUbuntu_14.04/Release.key'

matrix:
  include:
  - env: BUILD_TYPE=valgrind
    os: linux
    services: docker
    sudo: false
    compiler: gcc
    addons:
      apt:
        packages:
        - valgrind
        - uuid-dev
#        - asciidoc
#        - xmlto
  - env: BUILD_TYPE=valgrind
    os: linux
    services: docker
    sudo: false
    compiler: gcc
    addons:
      apt:
        packages:
        - valgrind
        - uuid-dev
        - libsodium-dev
  - env: BUILD_TYPE=valgrind
    os: linux
    services: docker
    sudo: false
    compiler: gcc
    addons:
      apt:
        sources: *pkg_src_zeromq_ubuntu14
        packages:
        - valgrind
        - uuid-dev
        - libsodium-dev

# Build and check this project according to the BUILD_TYPE
script: ./ci_build.sh
